# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd95ce214c8109e171fe5730a3772ea356efc319a294dda6b672a42f7db72509ee69c40443849b552fed2150bf4485f9c3620a727650d480f8b359e07b3bebae

test:
  secret_key_base: 40b98e29b61a0d8da312d93e36543d5d163600a09a4c8a071cbfb88eed9e5d9b768bc807df64b91bce9d25d0626564e4d9c871e79e6040dc4b3402b62a8c9b2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
